sudo: required

language: perl

perl : 
  - "5.22"

env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - NLS_LANG=AMERICAN_AMERICA.AL32UTF8
    - ORACLE_BASE=/u01/app/oracle
    - LD_LIBRARY_PATH=$ORACLE_HOME/lib
    - PATH=$PATH:$ORACLE_HOME/jdbc/lib:$ORACLE_HOME/bin
    - DATABASE_VERSION=11.2.0.2
    - ORACLE_SID=XE
    - DATABASE_NAME=XE
    - ORA_SDTZ='Europe/London' #Needed as a client parameter
    - TZ='Europe/London'       #Needed as a DB Server parameter
    - UT3_USER=ut3
    - UT3_PASSWORD=ut3
    - UT3_TABLESPACE=users

addons:
  apt:
    packages:
#packages required by oracle
      - bc
      - rpm
      - unzip
#      - libaio1


cache: 
  directories: 
    - .cache
    - $HOME/.cache

before_install:
  # perl modules needed for documenation generation
  - "cpanm IPC::System::Simple"
  - "cpanm Markdent"
# On trusty, download the zip file into a cachable directory
  - test "$DIST" = precise || export ORACLE_ZIP_DIR=$HOME/.cache
# If the zip file already exists, do not download it again
  - test -f "$ORACLE_ZIP_DIR"/$(basename $ORACLE_FILE) || bash .travis/oracle/download.sh

install:
  - bash .travis/oracle/install.sh

script:
  - bash .travis/create_utplsql_user.sh
  - bash .travis/install_libraries.sh
  - bash .travis/install.sh
  - bash .travis/run_examples.sh
  - bash .travis/run_test.sh
  - perl docsource/builddocs.pl

notifications:
  slack: utplsql:oiMuXO95TvKeAUENuDt4cPrB

